#!/usr/bin/env bash
#ridirections

config_file="/etc/nginx/sites-available/default"

sed -i '/location \/ {/a \
        location \/redirect_me { \
            return 301 https:\/\/example.com\/new-page; \
        }' "$config_file"

nginx -t

service nginx restart
