#!/usr/bin/env bash
#script to install and configure haproxy

PATH_TO_CFG="/etc/haproxy/haproxy.cfg"
REMOTE_USER="ubuntu"
REMOTE_HOST="100.25.146.195"
ssh "$REMOTE_USER"@"$REMOTE_HOST" "sudo apt-get update -y && sudo apt install haproxy -y"

CONFIG_CONTENT="
frontend my_frontend
	bind *:80
	mode http
	timeout client 10s
	default_backend my_servers

backend my_servers
	mode http
	timeout connect 20s
	balance roundrobin
	server 335068-web-01 54.160.118.189:80
	server 335068-web-02 34.229.67.177:80
	timeout server 20s
"
echo "$CONFIG_CONTENT" | ssh "$REMOTE_USER"@"$REMOTE_HOST" "sudo tee $PATH_TO_CFG > /dev/null && sudo haproxy -c -f $PATH_TO_CFG && sudo systemctl restart haproxy"
