#!/usr/bin/env bash
#script to create file ignore sigint and deletes the file if it recieves sigterm or sigquite

sudo chmod a+w /var/run/
file="/var/run/myscript.pid"
echo $$ > "$file"
clean_up(){
	echo "I hate the kill command"
	rm "$file"
	exit 1
}

cleanup(){
	echo "Y U no love me?!"
}

cleaning(){
	rm "$file"
        exit 1
}

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'clean_up' SIGTERM
	trap 'cleanup' SIGINT
	trap 'cleaning' SIGQUIT
done
