#!/usr/bin/env bash
#script to display /etc/passwd content in a story

filename="/etc/passwd"
while IFS=: read -r username password group_id user_id home_dir shell; do
	echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $user_id"
done < $filename
