#!/usr/bin/env bash
#configure firewall to block all incomming except port 22, 80 and 443

sudo apt install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

sudo ufw enable
sudo ufw default deny incoming

sudo ufw default allow outgoing

sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

sudo ufw enable
